AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyGoLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      FunctionName: my-go-lambda
      Runtime: go1.x
      CodeUri: .
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME: "products"  # Aquí puedes definir tus variables de entorno
      Policies:
        - AWSLambdaBasicExecutionRole  # Políticas básicas para ejecutar la función Lambda
        - AWSLambdaDynamoDBExecutionRole  # Si necesitas acceso a DynamoDB
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  MyLambdaFunctionArn:
    Description: "ARN de la función Lambda desplegada"
    Value: !GetAtt MyGoLambdaFunction.Arn
