AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ServerlessApiScraper:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      FunctionName: my-go-lambda
      Runtime: go1.x
      CodeUri: .
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 150
      Environment:
        Variables:
          TABLE_NAME: "products"
          DYNAMO_ENDPOINT: "http://host.docker.internal:8000"
      Policies:
        - AWSLambdaBasicExecutionRole 
        - AWSLambdaDynamoDBExecutionRole
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ServerlessApiScraperArn:
    Description: "ARN de la función Lambda desplegada"
    Value: !GetAtt ServerlessApiScraper.Arn
